export const category = [
  {
    id: 0,
    name: 'Sweets',
    icon: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 1,
    name: 'Sweets',
    icon: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 2,
    name: 'Sweets',
    icon: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 3,
    name: 'Sweets',
    icon: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 4,
    name: 'Sweets',
    icon: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 5,
    name: 'Sweets',
    icon: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 6,
    name: 'Sweets',
    icon: require('../assets/categories/icons8-pizza-96.png'),
  },
  {
    id: 7,
    name: 'Sweets',
    icon: require('../assets/categories/icons8-pizza-96.png'),
  },
];
export const featured = {
  id: 0,
  title: 'Hot and Spicy',
  description: 'soft and tender fried chicken',
  restaurants: [
    {
      id: 0,
      name: 'The GT Road',
      image: require('../assets/restaurants/download.jpeg'),
      lng: 77.22274139786053,
      lat: 28.63364302693495,
      address: 'M-39, Shankar Market, Block M New Delhi',
      stars: 4,
      reviews: '4.4k',
      category: 'fast food',
      dishes: [
        {
          id: 0,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/restaurants/rawImage.jpeg'),
        },
        {
          id: 1,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/restaurants/rawImage.jpeg'),
        },
        {
          id: 2,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/restaurants/rawImage.jpeg'),
        },
        {
          id: 3,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/restaurants/rawImage.jpeg'),
        },
        {
          id: 4,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/restaurants/rawImage.jpeg'),
        },
      ],
    },
    {
      id: 1,
      name: 'Pata Johns',
      image: require('../assets/restaurants/download.jpeg'),
      lng: 38.2145602,
      lat: -85.5324269,
      address: '424 second street',
      stars: 4,
      reviews: '4.4k',
      category: 'fast food',
      dishes: [
        {
          id: 0,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/restaurants/rawImage.jpeg'),
        },
        {
          id: 1,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/restaurants/rawImage.jpeg'),
        },
        {
          id: 2,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/restaurants/rawImage.jpeg'),
        },
        {
          id: 3,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/restaurants/rawImage.jpeg'),
        },
        {
          id: 4,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/restaurants/rawImage.jpeg'),
        },
      ],
    },
    {
      id: 2,
      name: 'Pata Johns',
      image: require('../assets/restaurants/download.jpeg'),
      lng: 38.2145602,
      lat: -85.5324269,
      address: '424 second street',
      stars: 4,
      reviews: '4.4k',
      category: 'fast food',
      dishes: [
        {
          id: 0,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/restaurants/rawImage.jpeg'),
        },
        {
          id: 1,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/restaurants/rawImage.jpeg'),
        },
        {
          id: 2,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/restaurants/rawImage.jpeg'),
        },
        {
          id: 3,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/restaurants/rawImage.jpeg'),
        },
        {
          id: 4,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/restaurants/rawImage.jpeg'),
        },
      ],
    },
  ],
};
